version: v1

data:
  input_csv: sample_data.csv
  schema: schema.example.yaml

validation:
  log: outputs/audit/validation.jsonl

outputs:
  dir: outputs

metrics:
  top_box_threshold: 4
  groupby:
    - region
    - gender

governance:
  retention_days: 365

charts:
  theme: chart_config.example.yaml
  specs:
    - id: satisfaction_by_segment
      kind: bar
      x: segment
      y: satisfaction
      aggregation: mean
      title: "Satisfaction by segment"
