name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy jinja2 pyyaml
      - name: Sample run
        working-directory: 02_advanced_pipeline
        run: python cli.py config.example.yaml
      - name: Integrity manifest
        run: |
          ls 02_advanced_pipeline/outputs | grep integrity.manifest || (echo "no integrity manifest" && exit 1)
      - name: Fairness parity present
        run: test -f 02_advanced_pipeline/outputs/fairness_parity.csv
